///////////////////////////////////////////////////////////
//  ExecussaoPontoDeColeta.cs
//  Implementation of the Class ExecussaoPontoDeColeta
//  Generated by Enterprise Architect
//  Created on:      20-abr-2017 13:10:17
//  Original author: silas
///////////////////////////////////////////////////////////


using System;
using Acme.GeoGarbage.Dominio.Enums;
namespace Acme.GeoGarbage.Dominio.Entidades
{
    /// <summary>
    /// Representa os pontos de coleta que devem ser realizados em uma operação de
    /// coleta.
    /// </summary>
    public class ExecucaoPontoDeColeta
    {
        public int IdExecucaoPontoDeColeta { get; set; }

        public int IdPontoDeColeta { get; set; }

        public Guid IdSetorDeJornada { get; set; }

        /// <summary>
        /// Ponto de coleta a ser realizado no setor.
        /// </summary>
        public virtual PontoDeColeta PontoDeColeta
        {
            get;
            set;
        }

        public virtual SetorDaJornada SetorDaJornada { get; set; }

        /// <summary>
        /// Indica o status de passagem no ponto de coleta.
        /// </summary>
        public StatusDePassagem StatusDePassagem
        {
            get;
            set;
        }

        /// <summary>
        /// Data/Hora da passagem pelo ponto.
        /// </summary>
        public DateTime Passagem
        {
            get;
            set;
        }

    }//end ExecussaoPontoDeColeta

}//end namespace Entidades