///////////////////////////////////////////////////////////
//  PontoDeColeta.cs
//  Implementation of the Class PontoDeColeta
//  Generated by Enterprise Architect
//  Created on:      20-abr-2017 13:10:17
//  Original author: silas
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;

namespace Acme.GeoGarbage.Dominio.Entidades
{
    /// <summary>
    /// Informações sobre ponto de coleta.
    /// </summary>
    public class PontoDeColeta
    {

        public int IdPontoDeColeta { get; set; }

        /// <summary>
        /// Sequencia de passagem no ponto em relação a um conjunto de pontos.
        /// </summary>
        public int SequenciaDeColeta { get; set; }
        /// <summary>
        /// Nome do ponto.
        /// </summary>
        public string Nome { get; set; }
        /// <summary>
        /// Latitude do ponto.
        /// </summary>
        public float Latitude { get; set; }
        /// <summary>
        /// Longitude do ponto.
        /// </summary>
        public float Longitude { get; set; }
        /// <summary>
        /// Horário de passagem no ponto no formato:
        /// hh:mm
        /// </summary>
        public string Horario { get; set; }
        /// <summary>
        /// 1ª Tolerância de passagem no ponto.
        /// Em minutos
        /// </summary>
        public int Tolerancia1 { get; set; }
        /// <summary>
        /// 2ª Tolerância de passagem no ponto.
        /// Em minutos.
        /// </summary>
        public int Tolerancia2 { get; set; }

        public Guid IdSetor { get; set; }

        public virtual Setor Setor { get; set; }
        public virtual IEnumerable<ExecucaoPontoDeColeta> ExecucaoPontoDeColetas { get; set; }

    }//end PontoDeColeta

}//end namespace Entidades