///////////////////////////////////////////////////////////
//  StatusConfiguracaoDevice.cs
//  Implementation of the Enumeration StatusConfiguracaoDevice
//  Generated by Enterprise Architect
//  Created on:      22-abr-2017 13:22:15
//  Original author: WILLIAMNOTE
///////////////////////////////////////////////////////////




namespace Acme.GeoGarbage.Dominio.Enums
{
	/// <summary>
	/// ChaveDeviceErrada = 1
	/// IdentificacaoNoClienteErrado = 2
	/// FalhaDeProcessamento = 3
	/// Sucesso = 4
	/// </summary>
	public enum StatusConfiguracaoDevice : int {

		ChaveDeviceErrada  = 1,
		IdentificacaoNoClienteErrado = 2,
		FalhaDeProcessamento = 3,
		Sucesso = 4

	}//end StatusConfiguracaoDevice

}//end namespace Enums