///////////////////////////////////////////////////////////
//  StatusDePassagem.cs
//  Implementation of the Class StatusDePassagem
//  Generated by Enterprise Architect
//  Created on:      20-abr-2017 13:54:09
//  Original author: silas
///////////////////////////////////////////////////////////


using System.ComponentModel;

namespace Acme.GeoGarbage.Dominio.Enums
{
    /// <summary>
    /// Lista de status possíveis para passagem por um ponto de coleta.
    /// </summary>
    public enum StatusDePassagem : int
    {

        /// <summary>
        /// Ponto a ser cumprido.
        /// </summary>
        [Description("A passar")]
        APassar = 1,
        /// <summary>
        /// Ponto não cumprido.
        /// </summary>
        [Description("Não cumprido")]
        NaoCumprido = 2,
        /// <summary>
        /// Ponto pulado.
        /// </summary>
        [Description("Pulado")]
        Pulado = 3,
        /// <summary>
        /// Passado pelo ponto.
        /// </summary>
        [Description("Passado")]
        Passado = 4

    }//end StatusDePassagem

}//end namespace Enums